-- AlterTable
ALTER TABLE `templates` MODIFY `type` ENUM('TOR', 'RAB', 'FORMAT_USULAN_PERBAIKAN', 'FORMAT_USULAN_BAHAN_HABIS', 'FORMAT_USULAN_PERALATAN', 'FORMAT_USULAN_PELATIHAN', 'FORMAT_USULAN_MEUBELAIR') NOT NULL;
